#!/usr/bin/env sh

# taps
brew tap homebrew/command-not-found
brew tap homebrew/services
brew tap homebrew/versions
brew tap homebrew/x11
brew tap neovim/neovim
brew tap rstacruz/backup

# packages
brew install aria2
brew install atk
brew install autoconf
brew install autojump
brew install automake
brew install aws-elasticbeanstalk
brew install awscli
brew install bdw-gc
brew install boost
brew install boost-python
brew install boot2docker
brew install cabal-install
brew install cabextract
brew install cairo
brew install cask
brew install cgal
brew install cheat
brew install chruby
brew install chruby-fish --HEAD
brew install cloc
brew install cmake
brew install cscope
brew install ctags
brew install deis
brew install deisctl
brew install direnv
brew install dirmngr
brew install docker
brew install docker-compose
brew install docker-machine
brew install doxygen
brew install emacs
brew install expat
brew install faac
brew install ffmpeg
brew install figlet
brew install fish --HEAD
brew install fontconfig
brew install fpp
brew install freetype
brew install freexl
brew install fzf
brew install gd
brew install gdal
brew install gdbm
brew install gdk-pixbuf
brew install geos
brew install gettext
brew install ghc
brew install ghub
brew install gifify
brew install giflib
brew install git
brew install git-cal
brew install git-extras
brew install git-fresh
brew install git-lfs
brew install github-release
brew install glib
brew install gmp
brew install gmp4
brew install gnome-icon-theme
brew install gnu-getopt
brew install gnupg
brew install gnupg2
brew install gnutls
brew install go
brew install gobject-introspection
brew install gpg-agent
brew install gpp
brew install graphicsmagick
brew install gsettings-desktop-schemas
brew install gtk+3
brew install gtksourceview3
brew install harfbuzz
brew install haskell-stack
brew install heroku-toolbelt
brew install hicolor-icon-theme
brew install htop-osx
brew install httpie
brew install hub
brew install icu4c
brew install imagemagick
brew install jasper
brew install jpeg
brew install jq
brew install json-c
brew install jsonpp
brew install lame
brew install ledger
brew install libassuan
brew install libcaca
brew install libepoxy
brew install libevent
brew install libffi
brew install libgcrypt
brew install libgeotiff
brew install libgpg-error
brew install libgphoto2
brew install libicns
brew install libksba
brew install liblwgeom
brew install libogg
brew install libpng
brew install libsass
brew install libspatialite
brew install libtasn1
brew install libtiff
brew install libtool
brew install libusb
brew install libusb-compat
brew install libvo-aacenc
brew install libvorbis
brew install libvpx
brew install libxml2
brew install libyaml
brew install links
brew install little-cms2
brew install lua
brew install luajit
brew install lzlib
brew install mackup
brew install macvim
brew install makedepend
brew install md5sha1sum
brew install meld
brew install mercurial
brew install mpfr
brew install mr
brew install mysql
brew install neovim --HEAD
brew install nettle
brew install ngrok
brew install ninja
brew install nmap
brew install node
brew install nvm
brew install oniguruma
brew install openssl
brew install optipng
brew install ossp-uuid
brew install p7zip
brew install pango
brew install pass
brew install pcre
brew install pcre2
brew install phantomjs192
brew install pinentry
brew install pixman
brew install pkg-config
brew install postgresql
brew install prettyping
brew install proj
brew install pth
brew install pwgen
brew install py2cairo
brew install pygobject3
brew install python
brew install python3
brew install ranger
brew install readline
brew install reattach-to-user-namespace
brew install redis
brew install ruby
brew install ruby-build
brew install ruby-install
brew install s3cmd
brew install sane-backends
brew install sassc
brew install sfcgal
brew install sift
brew install speedtest_cli
brew install sqlite
brew install ssh-copy-id
brew install subliminal
brew install task
brew install terminal-notifier
brew install texi2html
brew install the_silver_searcher
brew install tig
brew install tmux
brew install toilet
brew install tree
brew install unrar
brew install v8
brew install vit
brew install w3m
brew install wget
brew install wine
brew install winetricks
brew install x264
brew install xvid
brew install xz
brew install yasm
brew install youtube-dl
brew install zsh
