#!/usr/bin/env sh

# taps
brew tap aredridel/iojs
brew tap homebrew/services
brew tap homebrew/versions
brew tap homebrew/x11
brew tap neovim/neovim
brew tap rstacruz/backup

# packages
brew install aria2
brew install atk
brew install autoconf
brew install autojump
brew install automake
brew install aws-elasticbeanstalk
brew install awscli
brew install bdw-gc
brew install boost
brew install boost-python
brew install boot2docker
brew install brew-cask
brew install cairo
brew install cask
brew install cgal
brew install cheat
brew install chruby
brew install chruby-fish --HEAD
brew install cloc
brew install cmake
brew install cscope
brew install ctags
brew install deis
brew install deisctl
brew install direnv
brew install dirmngr
brew install docker
brew install docker-machine
brew install doxygen
brew install emacs
brew install expat
brew install faac
brew install ffmpeg
brew install fig
brew install fish
brew install fontconfig
brew install fpp
brew install freetype
brew install freexl
brew install gdal
brew install gdbm
brew install gdk-pixbuf
brew install geos
brew install gettext
brew install ghub
brew install gifify
brew install giflib
brew install git
brew install git-cal
brew install git-extras
brew install glib
brew install gmp
brew install gnome-icon-theme
brew install gnu-getopt
brew install gnupg
brew install gnupg2
brew install gnutls
brew install go
brew install gobject-introspection
brew install gpg-agent
brew install gpp
brew install graphicsmagick
brew install gsettings-desktop-schemas
brew install gtk+3
brew install gtksourceview3
brew install harfbuzz
brew install heroku-toolbelt
brew install hicolor-icon-theme
brew install htop-osx
brew install httpie
brew install hub
brew install icu4c
brew install imagemagick
brew install jpeg
brew install json-c
brew install lame
brew install ledger
brew install libassuan
brew install libepoxy
brew install libevent
brew install libffi
brew install libgcrypt
brew install libgeotiff
brew install libgpg-error
brew install libksba
brew install liblwgeom
brew install libogg
brew install libpng
brew install libsass
brew install libspatialite
brew install libtasn1
brew install libtiff
brew install libtool
brew install libusb
brew install libusb-compat
brew install libvo-aacenc
brew install libvorbis
brew install libvpx
brew install libxml2
brew install libyaml
brew install links
brew install lua
brew install luajit
brew install lzlib
brew install mackup
brew install md5sha1sum
brew install meld
brew install mercurial
brew install mpfr
brew install mr
brew install mysql
brew install neovim --HEAD
brew install nettle
brew install ninja
brew install nmap
brew install node
brew install nvm
brew install openssl
brew install optipng
brew install ossp-uuid
brew install pango
brew install pass
brew install pcre
brew install phantomjs192
brew install pinentry
brew install pixman
brew install pkg-config
brew install postgresql
brew install proj
brew install pth
brew install pwgen
brew install py2cairo
brew install pygobject3
brew install python
brew install python3
brew install readline
brew install reattach-to-user-namespace
brew install redis
brew install ruby
brew install ruby-build
brew install ruby-install
brew install s3cmd
brew install sassc
brew install sfcgal
brew install speedtest_cli
brew install sqlite
brew install ssh-copy-id
brew install subliminal
brew install terminal-notifier
brew install texi2html
brew install the_silver_searcher
brew install tig
brew install tmux
brew install tree
brew install v8
brew install w3m
brew install wget
brew install x264
brew install xvid
brew install xz
brew install yasm
brew install youtube-dl
brew install zsh
