#!/usr/bin/env sh

# taps
brew tap caskroom/cask
brew tap caskroom/fonts

# casks
brew cask install adobe-creative-cloud
brew cask install airfoil
brew cask install airserver
brew cask install alarm-clock
brew cask install alfred
brew cask install alternote
brew cask install android-studio
brew cask install appcleaner
brew cask install bartender
brew cask install barxtemp
brew cask install battle-net
brew cask install bettertouchtool
brew cask install carbon-copy-cloner
brew cask install cathode
brew cask install ccleaner
brew cask install cgoban
brew cask install chromium
brew cask install coconutbattery
brew cask install colloquy
brew cask install colorpicker-hex
brew cask install crashplan
brew cask install cyberduck
brew cask install deeper
brew cask install dockertoolbox
brew cask install dropbox
brew cask install evernote
brew cask install fantastical
brew cask install firefox
brew cask install flash-player
brew cask install fluid
brew cask install flux
brew cask install font-anonymous-pro-for-powerline
brew cask install font-arimo
brew cask install font-baron
brew cask install font-bebas-neue
brew cask install font-bitter
brew cask install font-clear-sans
brew cask install font-cousine
brew cask install font-dejavu-sans-mono-for-powerline
brew cask install font-droid-sans-mono-for-powerline
brew cask install font-fira-code
brew cask install font-fira-mono-for-powerline
brew cask install font-fira-sans
brew cask install font-hack
brew cask install font-hermit
brew cask install font-inconsolata-dz-for-powerline
brew cask install font-inconsolata-for-powerline
brew cask install font-inconsolata-g-for-powerline
brew cask install font-input
brew cask install font-jaapokki
brew cask install font-karla
brew cask install font-league-gothic
brew cask install font-league-script
brew cask install font-liberation-mono-for-powerline
brew cask install font-meddon
brew cask install font-merriweather
brew cask install font-meslo-lg-for-powerline
brew cask install font-monoid
brew cask install font-montserrat
brew cask install font-open-sans
brew cask install font-open-sans-condensed
brew cask install font-raleway
brew cask install font-roboto
brew cask install font-rokkitt
brew cask install font-sauce-code-powerline
brew cask install font-sinkin-sans
brew cask install font-source-code-pro
brew cask install font-source-sans-pro
brew cask install font-source-serif-pro
brew cask install font-terminus
brew cask install font-ubuntu
brew cask install font-ubuntu-mono-powerline
brew cask install font-work-sans
brew cask install gitter
brew cask install glyphs
brew cask install google-chrome
brew cask install google-drive
brew cask install gyazo
brew cask install isolator
brew cask install iterm2
brew cask install java
brew cask install karabiner
brew cask install keepingyouawake
brew cask install keyboard-cleaner
brew cask install kodi
brew cask install licecap
brew cask install little-snitch
brew cask install logitech-control-center
brew cask install macdown
brew cask install minecraft
brew cask install musescore
brew cask install nosleep
brew cask install numi
brew cask install playback
brew cask install plex-media-server
brew cask install qbittorrent
brew cask install reaper
brew cask install rightfont
brew cask install rowanj-gitx
brew cask install rss
brew cask install screenhero
brew cask install sketch
brew cask install sketch-toolbox
brew cask install skitch
brew cask install skype
brew cask install slack
brew cask install smoothmouse
brew cask install soulseek
brew cask install soundnode
brew cask install spectacle
brew cask install spotify
brew cask install steam
brew cask install techstoreclub-simple-comic
brew cask install the-unarchiver
brew cask install thyme
brew cask install transmission
brew cask install ubersicht
brew cask install unsplash-wallpaper
brew cask install viber
brew cask install virtualbox
brew cask install virtualbox-extension-pack
brew cask install vlc
brew cask install vox
brew cask install xquartz
brew cask install ynab
brew cask install yujitach-menumeters
