#!/usr/bin/sh
brew cask install affinity-designer-beta
brew cask install airfoil
brew cask install airserver
brew cask install alfred
brew cask install appcleaner
# brew cask install atom
brew cask install bartender
brew cask install bettertouchtool
brew cask install ccleaner
brew cask install chromium
brew cask install coconutbattery
brew cask install colloquy
brew cask install colorpicker-hex
brew cask install cyberduck
brew cask install facebook-messenger-desktop
brew cask install firefox
brew cask install fluid
brew cask install flux
brew cask install font-bebas-neue
brew cask install font-bitter
brew cask install font-clear-sans
brew cask install font-cousine
brew cask install font-fira-code
brew cask install font-fira-sans
brew cask install font-hermit
brew cask install font-karla
brew cask install font-league-gothic
brew cask install font-league-script
brew cask install font-meddon
brew cask install font-merriweather
brew cask install font-meslo-lg-for-powerline
brew cask install font-montserrat
brew cask install font-raleway
brew cask install font-rokkitt
brew cask install font-sauce-code-powerline
brew cask install font-source-code-pro
brew cask install font-source-code-pro-for-powerline
brew cask install font-terminus
brew cask install font-ubuntu
brew cask install github
brew cask install gitter
brew cask install google-chrome
brew cask install gyazo
brew cask install iterm2
brew cask install karabiner
brew cask install keepingyouawake
brew cask install licecap
brew cask install macdown
brew cask install monotype-skyfonts
brew cask install nosleep
brew cask install noun-project
brew cask install numi
brew cask install onyx
brew cask install rowanj-gitx
brew cask install screenhero
brew cask install sketch
brew cask install sketch-beta
brew cask install sketch-toolbox
brew cask install skitch
brew cask install skype
brew cask install smoothmouse
brew cask install spectacle
brew cask install techstoreclub-simple-comic
brew cask install the-unarchiver
brew cask install thyme
brew cask install transmission
brew cask install ubersicht
brew cask install vagrant
brew cask install viber
brew cask install virtualbox
brew cask install vlc
brew cask install vlcstreamer
brew cask install wakeonlan
brew cask install xquartz
