tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'd12frosted/emacs-plus'
tap 'homebrew/boneyard'
tap 'homebrew/bundle'
tap 'homebrew/command-not-found'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'homebrew/versions'
tap 'homebrew/x11'
tap 'rstacruz/backup'
# brew 'libyaml' # dependents: ansible, ruby
# brew 'openssl@1.1' # dependents: ansible, wget
# brew 'python' # dependents: gsettings-desktop-schemas
brew 'ansible'
brew 'aria2'
# brew 'gettext' # dependents: coreutils, fontforge, git, gnu-getopt, gnupg, gsettings-desktop-schemas, libgphoto2, neovim, texi2html, utimer, wget, yasm
# brew 'fontconfig', args: ['universal'] # dependents: emacs-plus, ffmpeg, fontforge, gd, imagemagick
brew 'pixman'
brew 'git'
# brew 'atk' # dependents: gtk+3
# brew 'autoconf' # dependents: automake, coreutils, ctags, emacs, emacs-plus, erlang, faac, fish, fontconfig, gd, gdal, ghc, ghostscript, graphviz, hicolor-icon-theme, htop-osx, jq, json-c, libcaca, libgeotiff, libgphoto2, liblwgeom, libogg, libsodium, libspatialite, libssh2, libvorbis, libxml2, postgis, proj, ruby, ruby-build, the_silver_searcher, tig, tmate, tmux, watchman, wget, yasm, zeromq, zsh
brew 'autojump'
# brew 'automake' # dependents: coreutils, erlang, faac, fish, fontconfig, gd, gdal, ghc, ghostscript, graphviz, hicolor-icon-theme, htop-osx, jq, json-c, libcaca, libgeotiff, libgphoto2, liblwgeom, libogg, libsodium, libspatialite, libssh2, libvorbis, libxml2, postgis, proj, the_silver_searcher, tig, tmate, tmux, watchman, wget, yasm, zeromq
brew 'aws-elasticbeanstalk'
brew 'awscli'
# brew 'ghc' # dependents: cabal-install, hledger
# brew 'cabal-install' # dependents: hledger, pandoc
# brew 'cabextract' # dependents: winetricks
# brew 'mpfr' # dependents: cgal, sfcgal
# brew 'cgal' # dependents: sfcgal
# brew 'chruby' # dependents: chruby-fish
# brew 'fish' # dependents: chruby-fish
brew 'chruby-fish', args: ['HEAD']
brew 'cloc'
brew 'coreutils'
brew 'cpulimit'
brew 'cputhrottle'
# brew 'cscope' # dependents: macvim
brew 'ctags'
brew 'direnv'
# brew 'libassuan' # dependents: dirmngr, gnupg, gpg-agent
# brew 'libksba' # dependents: dirmngr, gnupg, gpg-agent
# brew 'pth' # dependents: dirmngr, gpg-agent
brew 'dirmngr'
brew 'elasticsearch', restart_service: true
# brew 'jpeg', args: ['universal'] # dependents: fontforge, gd, gdal, graphicsmagick, imagemagick, jasper, libgeotiff, sane-backends, wxmac
# brew 'wxmac' # dependents: erlang
brew 'erlang'
brew 'elixir'
brew 'emacs'
brew 'entr'
brew 'faac'
# brew 'lame' # dependents: ffmpeg
# brew 'x264' # dependents: ffmpeg
# brew 'xvid' # dependents: ffmpeg
brew 'ffmpeg'
brew 'figlet'
# brew 'libtool', args: ['universal'] # dependents: erlang, faac, fontconfig, fontforge, gd, gdal, ghc, ghostscript, graphicsmagick, graphviz, htop-osx, imagemagick, jq, json-c, libcaca, libgeotiff, libgphoto2, liblwgeom, libogg, libsodium, libspatialite, libssh2, libvorbis, libxml2, postgis, proj, tmate, tmux, watchman, zeromq
brew 'fontforge'
# brew 'freexl' # dependents: gdal, libspatialite
brew 'fzf'
# brew 'gd', args: ['universal'] # dependents: graphviz, libgphoto2
# brew 'geos' # dependents: gdal, liblwgeom, libspatialite, postgis
# brew 'giflib' # dependents: fontforge, gdal
# brew 'json-c' # dependents: gdal, liblwgeom, postgis
# brew 'proj' # dependents: gdal, libgeotiff, liblwgeom, libspatialite, postgis
# brew 'libgeotiff' # dependents: gdal
# brew 'liblwgeom' # dependents: libspatialite
# brew 'libxml2' # dependents: gdal, gettext, libspatialite
# brew 'libspatialite' # dependents: gdal
# brew 'gdal' # dependents: postgis
# brew 'ghostscript' # dependents: graphicsmagick, imagemagick
brew 'git-cal'
brew 'git-extras'
brew 'git-fresh'
brew 'git-lfs'
brew 'github-release'
brew 'gmp@4'
# brew 'gnu-getopt' # dependents: pass
# brew 'gnu-sed', args: ['with-default-names'] # dependents: emacs, emacs-plus
brew 'gnupg'
# brew 'go' # dependents: direnv, fzf, git, git-lfs, github-release, godep, hub, terraform
brew 'godep'
brew 'gpg-agent'
brew 'graphicsmagick'
# brew 'graphviz' # dependents: postgis
# brew 'gsettings-desktop-schemas' # dependents: gtk+3
# brew 'hicolor-icon-theme' # dependents: gtk+3
# brew 'libepoxy' # dependents: gtk+3
brew 'gtk+3'
brew 'heroku'
# brew 'lua' # dependents: highlight, macvim
brew 'highlight'
brew 'hledger'
brew 'htop-osx'
brew 'httpie'
brew 'hub'
# brew 'imagemagick' # dependents: postgis
# brew 'jasper', args: ['universal'] # dependents: gdal, graphicsmagick, gtk+3, libicns
# brew 'oniguruma' # dependents: jq
brew 'jq'
brew 'jsonpp'
# brew 'libcaca' # dependents: ffmpeg, toilet
# brew 'libusb-compat', args: ['universal'] # dependents: libgphoto2
brew 'libgphoto2', args: ['universal']
brew 'libicns', args: ['universal']
# brew 'libogg' # dependents: libvorbis
# brew 'libsodium' # dependents: zeromq
# brew 'libssh2' # dependents: aria2, rust
brew 'libvo-aacenc'
# brew 'libvorbis' # dependents: ffmpeg
# brew 'libvpx' # dependents: ffmpeg
brew 'lsusb'
# brew 'luajit' # dependents: macvim, neovim
brew 'lzlib'
brew 'mackup'
brew 'macvim', args: ['with-lua', 'with-override-system-vim', 'with-python3']
# brew 'makedepend' # dependents: wine
brew 'md5sha1sum'
# brew 'mysql' # dependents: gdal
brew 'neovim'
brew 'neovim-dot-app'
brew 'netperf'
brew 'nmap'
brew 'nvm'
brew 'optipng'
# brew 'p7zip' # dependents: winetricks
# brew 'pandoc' # dependents: youtube-dl
# brew 'tree' # dependents: pass
brew 'pass'
brew 'phantomjs'
brew 'pinentry-mac'
# brew 'postgresql', restart_service: true # dependents: gdal, liblwgeom, postgis
# brew 'sfcgal' # dependents: postgis
brew 'postgis'
brew 'pwgen'
brew 'reattach-to-user-namespace'
brew 'redis', restart_service: true
# brew 'ruby' # dependents: graphviz
brew 'ruby-build'
brew 'rust'
brew 's3cmd'
brew 'sane-backends', args: ['universal']
brew 'siege'
# brew 'sphinx-doc' # dependents: ghc, python
brew 'ssh-copy-id'
brew 'subliminal'
brew 'terminal-notifier'
brew 'terraform'
# brew 'texi2html' # dependents: ffmpeg
brew 'the_silver_searcher'
brew 'tig'
brew 'tmate'
brew 'tmux'
brew 'toilet'
# brew 'unrar' # dependents: winetricks
brew 'utimer'
brew 'v8'
brew 'watchman'
# brew 'wget' # dependents: coreutils
# brew 'wine' # dependents: winetricks
brew 'winetricks'
brew 'yarn'
# brew 'yasm' # dependents: ffmpeg, libvpx, x264
brew 'youtube-dl'
# brew 'zeromq' # dependents: ffmpeg
brew 'zsh'
brew 'd12frosted/emacs-plus/emacs-plus'
